#!/bin/bash

# [[ -f ~/.config/bspwm/!window_gap ]] && window_gap=$(desktop_margin) || \
#     window_gap=40 # default

bspc config border_width          2
# bspc config focused_border_color  '#404E5E'
bspc config normal_border_color  '#262626'
bspc config active_border_color '#3a3a3a'
bspc config focused_border_color '#545350'
# bspc config focused_border_color '#a3a3ab'
# bspc config focused_sticky_border_color '#404E5E'
bspc config focused_sticky_border_color '#010101'
bspc config focused_private_border_color '#a3a3ab'
bspc config presel_feedback_color '#a3a3ab'
# bspc config window_gap            $window_gap
# bspc config window_gap            $window_gap
bspc config window_gap            20

#bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config auto_cancel true
bspc config history_aware_focus true

bspc config top_padding         80
bspc config bottom_padding      60
bspc config left_padding        60
bspc config right_padding       60
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true

bspc config external_rules_command $(which autotile)

#bspc monitor -d $(echo -e '\uf120') $(echo -e '\uf121') $(echo -e '\ue600') $(echo -e '\uf084') $(echo -e '\uf005') $(echo -e '\ue602') $(echo -e '\uf108')

bspc rule -a ncmpcpp state=floating
bspc rule -a mpv state=floating

bspc rule -a vlc state=floating

desktops=($(bspc query -M))

# determine if this is initial run by seeing if monitors have been renamed to numbers yet
echo "$desktops" | grep -q "[a-zA-Z]"
if [ $? -eq 0 ]; then IsInitialRun=true; else IsInitialRun=false; fi

# rename all the monitors to numbers and create 5 workspaces on each
i=1

# for monitor in $desktops; do
#     [ "$IsInitialRun" = true ] && \
#         bspc monitor "$monitor" -n $i -d $i/{00,01,10,11} || \
#         bspc monitor "$monitor" -d $i/{00,01,10,11}
#     let i++
# done

# get a list of desktops in monocle mode:
MonocleDesktops=''
for desktop in $(bspc query -D); do
    [ ! -z "$( bspc query -d $desktop -T | grep "M - \*")" ] && MonocleDesktops="$MonocleDesktops $desktop"
done

if [ ${#desktops[@]} -eq 2 ]; then
    bspc monitor ${desktops[0]} -n 1 -d 一 二 三 四;
    bspc monitor ${desktops[1]} -n 2 -d 五 六 七 八;
else
    bspc monitor ${desktops[0]} -n 1 -d 一 二 三 四 五 六 七 八;
fi

# Set any Monocle desktops back to tiling mode
for desktop in $MonocleDesktops; do
    bspc desktop $desktop -l monocle
done

panel &
# window_gap --daemon &
#nm-applet &
#sleep 6 && stalonetray
